version: '3.4'
services:
  virtualbazaar:
    image: virtualbazaar
    build:
      context: .
      dockerfile: VirtualBazaar/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
        - ./images:/app/wwwroot/images