services:
  virtualbazaar:
    image: virtualbazaar
    build:
      context: .
      dockerfile: VirtualBazaar/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Virtu@lBaz@r2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
volumes:
  dbdata: